version: 2
jobs:
  build:
    docker:
      - image: vulture/gcc-valgrind-cunit
    steps:
      - checkout
      - run:
          name: display Env
          command: set
      - run:
          name: Make on vulture/gcc-valgrind-cunit
          command: make
      - run:
          name: Exec on vulture/gcc-valgrind-cunit
          command: cunit_test	  

