version: 2
jobs:
  build:
    docker:
      - image: vulture/gcc-valgrind-cunit
    steps:
      - checkout
      - run:
          name: display Env
          command: set && ls -la
      - run:
          name: Make on vulture/gcc-valgrind-cunit
          command: make
      - run:
          name: display Env after make
          command: ls -lar
      - run:
          name: Exec on vulture/gcc-valgrind-cunit
          command: ./cunit_test	  

