version: 2
jobs:
  build:
    docker:
      - image: vulture/gcc-valgrind-cunit
    steps:
      - checkout
      - run:
          name: Make on vulture/gcc-valgrind-cunit
          command: make
          command: cunit_test	  
      - run:
          name: Print the Current Time
          command: date
